#!/usr/bin/env bash

#
# Install git
#

SUDO=${CH_SUDO:-sudo}

if [ -x "$(command -v pacman)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO pacman -S --needed --noconfirm git
elif [ -x "$(command -v apt)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO apt install git -y
fi

#
# Install GitHub CLI (gh)
#

if [ ! -x "$(command -v gh)" ]; then
  if [ -x "$(command -v brew)" ]; then
    brew install gh
  elif [ -x "$(command -v apt)" ]; then
    $SUDO apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
    $SUDO apt-add-repository https://cli.github.com/packages
    $SUDO apt update
    $SUDO apt install gh -y
  elif [ -x "$(command -v yum)" ]; then
    $SUDO rpm -Uvh https://cli.github.com/packages/github-cli-release.rpm
    $SUDO yum install gh -y
  elif [ -x "$(command -v pacman)" ]; then
    $SUDO pacman -S --needed --noconfirm gh
  fi
fi

#
# Clone Rosnehook
#

git clone --depth 1 https://github.com/RosneBurgerworks/rosnehook

#
# Run Rosnehook's install all script
#

pushd rosnehook
bash ./install-all
popd
