#!/usr/bin/env bash

#
# Install git
#

SUDO=${CH_SUDO:-sudo}

if [ -x "$(command -v pacman)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO pacman -S --needed --noconfirm git
elif [ -x "$(command -v apt)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO apt install git -y
fi

#
# clone rosnebot-database
#

git clone --recursive https://github.com/RosneBurgerworks/rosnebot-database

#
# copy navs to TF2 maps
#

$SUDO cp -R rosnebot-database/nav\ meshes/* ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps
$SUDO chmod 755 -R ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps

#
# delete rosnebot-datbase
#

$SUDO rm -rf rosnebot-database

#
# Clone Darkerhook
#

git clone --depth 1 https://github.com/ScriptedRoFLaN/DarkerhookRebirth

#
# Run Darkerhook's install all script
#

pushd DarkerhookRebirth
bash ./install-all
popd
